server {
    listen 80;
    server_name localhost;

    client_max_body_size 10M;

    root /var/www/public;
    index index.php index.html;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        # Docker internal DNS
        resolver 127.0.0.11 valid=30s;
        set $upstream php:9000;
        
        include fastcgi_params;
        fastcgi_pass $upstream;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\. {
        deny all;
    }
}